export const FETCH_LISTS = 'FETCH_LISTS'
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS'
export const FETCH_LISTS_ERROR = 'FETCH_LISTS_ERROR'

export const POST_LIST = 'POST_LIST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_ERROR = 'POST_LIST_ERROR'
